---
deployment:
  tasks:
    - name: Install dependencies
      command: yarn install
    - name: Build app
      command: yarn build
    - export DEPLOYPATH=/home/travdxpu/repositories/travis-martin-portfolio/
    - /bin/cp -R images $DEPLOYPATH
